# Generated by Django 2.0.5 on 2018-06-02 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='crew',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='flight',
        ),
        migrations.RemoveField(
            model_name='crew',
            name='flight',
        ),
        migrations.AddField(
            model_name='flight',
            name='crew',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='crew', to='flights.Crew'),
        ),
        migrations.DeleteModel(
            name='Contract',
        ),
    ]
