# Generated by Django 2.0.5 on 2018-05-19 10:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airplane',
            name='capacity',
            field=models.IntegerField(default=25),
        ),
        migrations.AddField(
            model_name='flight',
            name='arrival_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flight',
            name='departure_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
