# Generated by Django 2.0.5 on 2018-05-19 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_auto_20180519_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airplane',
            name='official_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='airport',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='airport',
            name='country',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='surname',
            field=models.CharField(max_length=100),
        ),
    ]
